- cornice/tests/test_validation.py
- cornice/validators.py
- tox.ini
While using angular to make POST request I've noticed a warning:
> 2014-10-12 21:28:12,091 WARNI [cornice][Dummy-2] returning a json string or array is a potential security hole, please ensure you really want to do this.
After some investigation I realised that this is because response to OPTIONS request had an empty body `b'""'`. If I'm not mistaken, angular makes this request before POSTing data. Would it be better if cornice(?) returned an empty object `{}`?
To replicate this warning define any resource. Add `cors_origins=('*',)` option, and then make a call, for example, with `curl`:
> curl -X OPTIONS -H "Origin:http://localhost:6543/" -H "Access-Control-Request-Method:OPTIONS" localhost:6543/api/v1/notes
And you'll get a warning from cornice.
> Empty response to OPTIONS request

- cornice/service.py
- cornice/tests/test_cors.py
When a view raises an exception or returns a Response object, cors allow-origin headers are not set. This PR makes sure the headers are set.
> Set cors headers when a response is returned or exception is raised

- cornice/pyramidhook.py
- cornice/tests/ext/test_spore.py
- cornice/tests/test_cors.py
Because browser doesn't send Authorization headers on OPTIONS call.
> When using set_default_permissions OPTIONS calls for CORS does not work anymore.

- cornice/service.py
- cornice/tests/test_service.py
Fix crash with ``Service.cors_max_age_for()`` and ``Service.cors_support_credentials()``
> Safety check on CORS methods in Service

- cornice/cors.py
- cornice/service.py
- cornice/tests/test_cors.py
- cornice/tests/test_service.py
Fix proposal of https://github.com/mozilla-services/cliquet/issues/54
*caution*, this is a violent change, breaking the Service API (from property to class method)
> Service.cors_supported_headers are now filtered by method

- cornice/ext/sphinxext.py
When a default value exists for a schema attribute, display it instead of just
showing it is optional.
> sphinx extension: display default values

- docs/source/tutorial.rst
I believe we should strike "simply", "easily", and "obviously" from all tutorials or presentations.  :-)  I'm working through cornice now and just thought I'd provide a tad of cleanup.
> "Simply" is redundant and well, not accurate.

- cornice/resource.py
- cornice/tests/test_resource.py
Warn the user when `collection_path == path`. See #290
> Add resource path warning

- cornice/tests/test_resource.py
Running my own tests I got a failure on `test_basic_resource` using py34 and pyramid==1.5.7.  The message I got was this:
```
======================================================================
FAIL: test_basic_resource (cornice.tests.test_resource.TestResource)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/tim/cornice/cornice/tests/test_resource.py", line 119, in test_basic_resource
self.assertEqual(resp.body, b'test({"name": "gawel"});', resp.body)
AssertionError: b'/**/test({"name": "gawel"});' != b'test({"name": "gawel"});' : b'/**/test({"name": "gawel"});'
----------------------------------------------------------------------
```
Instead of adding another branch on the if statement for that particular version, …
> make test less dependent on pyramid version

- cornice/ext/sphinxext.py
- cornice/tests/ext/test_sphinxext.py
Python 3 does not have the `reload` built-in.  As of Python 3.4, `reload` is available in `importlib`, see
https://docs.python.org/3/library/importlib.html#importlib.reload.
A test is included that shows the breakage/fix.  I'll be happy to make any additional changes requested.
> Import reload for Python 3

- cornice/schemas.py
- cornice/tests/test_schemas.py
fixes: #307
Unfortunately I didn't have the time to fully understand the code and try to do duck typing.  Right now it uses the `unknown` property that only really exists on the `Mapping` type.  The major thing is a SchemaNode(Mapping()) will now work.
> Fix schema typing

- cornice/cors.py
- cornice/tests/test_cors.py
As per my submission of #319, I was hitting  CORS issue when using credentials.  In particular, I get the following error:
> XMLHttpRequest cannot load '....' A wildcard '*' cannot be used in the 'Access-Control- Allow-Origin' header when the credentials flag is true. Origin '....' is therefore not allowed access.
What I think should be happening is the server should be setting the 'Access-Control-Allow-Origin' response header to the origin provided in the credentialed request. I've replaced an incorrect check of a request header, Access-Control-Allow-Credentials, which is really a response header with a correct test on the service definition.
> fix check for cors allow credentials

- cornice/service.py
- cornice/tests/test_service.py
Otherwise the header is always present a `False` value.
> Fix Access-Control-Max-Age value if undefined on service

- CONTRIBUTORS.txt
- cornice/__init__.py
- cornice/ext/sphinxext.py
- cornice/pyramidhook.py
- cornice/resource.py
- cornice/tests/ext/dummy/__init__.py
- cornice/tests/ext/dummy/views.py
- cornice/tests/ext/test_sphinxext.py
- cornice/tests/test_imperative_resource.py
- docs/source/resources.rst
- docs/source/sphinx.rst
See issue #334 for more info. Coverage for sphinxext increased to 60% :)
> adding abillity to define services imperative

- cornice/schemas.py
- cornice/tests/test_schemas.py
I have a schema like the following:
class TestNoneSchema(MappingSchema):
foo = SchemaNode(String())
bar = SchemaNode(Sequence(), SchemaNode(String()), missing=None)
When I try to validate a JSON body where `bar` is `null` (for example `'{"foo": "abc", "bar": null}'`), the validation returns the following error:
[{'name': 'bar', 'location': 'body', 'description': u'"None" is not iterable'}]
This is because Cornice calls `deserialize` in [validate_colander_schema](https://github.com/mozilla-services/cornice/blob/c71b5c4fb25c70a62b203c9480810ec8707878bf/cornice/schemas.py#L146) with `None` instead of `colander.null`. Because [Sequence.serialize](https://github.com/Pylons/colander/blob/master/colander/__init__.py#L1058-L1079) only checks for `colander.null`, an exception is thrown.
As far as …
> Convert None to null before calling deserialize

- cornice/__init__.py
- cornice/schemas.py
- cornice/tests/test_validation.py
- cornice/tests/validationapp.py
- docs/source/validation.rst
Fix #200
After investigating the issue further, I realized that not everything can be done by Colander. Colander can only provide translation strings but it cannot perform the translation itself because it doesn't depend on Pyramid and doesn't know about localizers. As suggested earlier, I've proposed a change to Colander so that we can pass a translation callable to the ``asdict`` method: https://github.com/Pylons/colander/pull/157
However it's still up to Cornice to provide a callback that is aware of the current locale.
Since Cornice aims at following HTTP conventions, I've added support for the HTTP ``Accept-Language`` header. I've also added some configuration code that sets up a localizer depending on configuration variables based on suggestions from the Pyramid documentation:
* …
> Allow i18n of colander error messages

- cornice/ext/sphinxext.py
- cornice/tests/ext/dummy/views.py
- cornice/tests/ext/test_sphinxext.py
Currently in sphinxext, validators defined as strings in a resource or service are rendered directly as `str.__doc__` e.g.
user_info = Service(name='users', path='/{username}/info',
validators=('validate'))
will render:
"str(object='') -> string\n\nReturn a nice string representation of the object.\nIf the argument is a string, the return value is the same object."
This branch provides a fix and a relevant test, type checking strings and ensuring the validator object's `__doc__` is rendered. String to object resolution, also required to render views, has been factored out to a new method, `_resolve_obj_to_docstring`.
This branch also contains some mostly cosmetic refactoring of the sphinext tests.
> String validators rendered as str.__doc__ in sphinxext

- docs/source/testing.rst
This typo in [Testing example](https://cornice.readthedocs.org/en/latest/testing.html) caused pserve to fail with `pyramid.exceptions.ConfigurationError: Unknown predicate values: {'validator': <function has_payed at 0x7fb14c54f500>}`
> Incorrect attribute 'validator' replaced with 'validators'

- docs/source/validation.rst
Without the decorator, the second argument is not `kw` but the actual value of the node.
> Clarify docs for deferred colander validator

- CHANGES.txt
- cornice/tests/test_validation.py
- cornice/tests/validationapp.py
- cornice/util.py
Improve and resolve #343, add appropriate tests.
> properly handle content_type callables returning a single internet media type as scalar

- cornice/pyramidhook.py
- cornice/tests/test_validation.py
Return a 415 error response, if and only if there is some content.
@almet r?
> Do not raise a 415 error when no content-type and no body

- CHANGES.txt
- cornice/errors.py
- cornice/pyramidhook.py
The errors list is accessed via ``request.errors``, it makes thus no sense to store a circular reference.
And «Look mum, no tests fail!» (*ie. no spec was changed*)
@Natim r?
> Remove request from errors list (fixes #328)

- docs/source/index.rst
- docs/source/upgrading.rst
> Add upgrading docs for major versions (fixes #385)

- CHANGES.txt
- cornice/errors.py
- cornice/tests/test_errors.py
- docs/source/validation.rst
If this conflicts with your PR @tarekziade, do not take it into account, I'll rebase it later.
r?
> Only accept known locations in request.errors.add() (fixes #99)

- cornice/tests/test_validation.py
- cornice/tests/validationapp.py
- cornice/validators/__init__.py
- cornice/validators/_colander.py
- docs/source/builtin-validation.rst
- docs/source/upgrading.rst
> Add colander_body_validator (fixes #386)

- CHANGES.txt
- cornice/validators/__init__.py
- tests/test_validation.py
> Fix truncated JSON validation error message

- CHANGES.txt
- cornice/validators/__init__.py
- tests/test_validation.py
- tests/validationapp.py
Change ``extract_cstruct`` so as to put ``request.matchdict`` (rather than ``request.path``) into ``cstruct['path']``.
This is to maintain semantic consistency with Cornice 1.2, where ``location='path'`` meant to extract parameters from ``matchdict``.
See #411 for further discussion.
> Restore old semantics of location='path'

- CHANGES.txt
- cornice/validators/_colander.py
- docs/source/schema.rst
- docs/source/upgrading.rst
- tests/test_colander.py
- tests/validationapp.py
Previously, ``colander_validator`` (and ``colander_body_validator``) expected ``schema`` to be a colander schema class.  This change supports setting ``schema`` to a schema node (or instance.)
This behavior is more flexible.  (Schema node instances can be constructed in a variety of ways, including [imperative definition](http://docs.pylonsproject.org/projects/colander/en/latest/basics.html#defining-a-schema-imperatively), and [schema binding](http://docs.pylonsproject.org/projects/colander/en/latest/binding.html).)
Also, now, a ``DeprecationWarning`` is issued when ``schema`` is set to a class rather than an instance.
See #412 for further discussion.
> Support passing colander schema nodes (instances)

- cornice/tests/test_util.py
- cornice/util.py
If you look at the current impl of `util.extract_json_data` it passes request.body directly to `simplejson.loads`.
Under PY2, when passed a string, `loads` has the [documented behaviour](https://simplejson.readthedocs.io/en/latest/#simplejson.loads) of varying the type of returned string values depending on the content of the strings:
> If s is a str then decoded JSON strings that contain only ASCII characters may be parsed as str for performance and memory reasons. If your code expects only unicode the appropriate solution is decode s to unicode prior to calling loads.
You can see the behaviour with e.g.:
```
>>> import simplejson
>>> simplejson.loads('{"foo":"ear"}')
{'foo': 'ear'}
>>> simplejson.loads('{"foo":"€ar"}')
{'foo': u'\u20acar'}
>>> simplejson.loads(u'{"foo":"ear"}')
{u'foo': …
```
> Make sure JSON string values come through consistently as unicode.

- CHANGES.txt
- CONTRIBUTORS.txt
- cornice/cors.py
- tests/test_cors.py
Cornice parses this header by using the non flexible way as HTTP specification
required. Specifications says Access-Control-Request-Headers header
can have any number of LWS (Linear White Spaces) between commas.
But Cornice strictly waits for 'comma with space' delimiter.
It leads to an error for header values like
`Access-Control-Request-Headers: header1,header2,header3` when 
`cors_expose_all_headers=True`, even if any of these headers (or all of them) 
persist in `service.cors_headers` attribute.
Is it necessary to write tests for this situation? (I see no such tests for other headers)
> Fix parsing of 'Access-Control-Request-Headers' header

- CHANGES.txt
- cornice/pyramidhook.py
- cornice/service.py
- tests/test_service.py
Some explanation here:
* some parts of the code were relying on the fact that `acl` and `factory` were passed as view args (and removed at last moment). 
* I changed the code so that `acl` and `factory` never end-up as view arguments (as introduced in version 1.0)
> Fix inconsistency in cornice.service.decorate_view() arguments

- CHANGES.txt
- CONTRIBUTORS.txt
- cornice/validators/__init__.py
- tests/test_validation.py
This adds support to a [series of JSON Content-Type variations](http://www.iana.org/assignments/media-types/media-types.xhtml#application) which can be validated as common JSON requests.
Original issue: https://github.com/Kinto/kinto/issues/979
Related to: https://github.com/Kinto/kinto/pull/981
r? @leplatrem
> Add custom JSON content-type support

- setup.py
I noticed today that Cornice does not work with Pyramid 1.5, as it
tries to configure Pyramid with require_csrf which was introduced
in Pyramid 1.7[0]. If this minimum version of Pyramid is not used,
users will receive Tracebacks similar to this:
Traceback (most recent call last):
File "/usr/bin/pserve", line 9, in <module>
load_entry_point('pyramid', 'console_scripts', 'pserve')()
File "/usr/lib/python2.7/site-packages/pyramid/scripts/pserve.py", line 58, in main
return command.run()
File "/usr/lib/python2.7/site-packages/pyramid/scripts/pserve.py", line 328, in run
global_conf=vars)
File "/usr/lib/python2.7/site-packages/pyramid/scripts/pserve.py", line 363, in loadapp
return loadapp(app_spec, name=name, relative_to=relative_to, **kw)
File …
> Configure setup.py to require a minimum version of Pyramid at 1.7.

- setup.py
Two modules import venusian, but it wasn't required in the
setup.py. This commit adds it there.
> Require venusian in setup.py.

- cornice/pyramidhook.py
- cornice/resource.py
- cornice/service.py
- cornice/util.py
- tests/test_pyramidhook.py
- tests/test_resource.py
- tests/test_service.py
Services: allow services to reuse existing pyramid routes instead ofcreating new ones every time
I believe this will fix: 
https://github.com/Cornices/cornice/issues/137 and https://github.com/Cornices/cornice/issues/473 among things.
> allow services to reuse existing pyramid routes instead ofcreating new ones every time

- cornice/resource.py
- docs/source/resources.rst
- docs/source/services.rst
This should make the feature complete with examples.
> docs: add examples on how to reuse pyramid routes

- cornice/util.py
- docs/source/validation.rst
- tests/test_imperative_resource.py
- tests/test_resource.py
- tests/test_resource_callable.py
- tests/test_service.py
- tests/test_validation.py
- tests/validationapp.py
Remove `text/json` - replace with `text/plain` and/or `application/json` according to each scenario.
Worth mentioning https://github.com/Cornices/cornice/issues/470#issuecomment-365315313
> content-type/accept `text/json`?

- .travis.yml
- CHANGES.txt
- CONTRIBUTORS.txt
- cornice/errors.py
- tests/test_validation.py
The aim of this is to make more use of the _json_ module from the standard library instead of the external _simplejson_ module.
This prepares closing #418 but because of problems mentioned in that issue this isn't yet a full switch.
It also enables tests with Python 3.7.
> Reducing simplejson use

- cornice/service.py
This became a warning as of Python 3.6 -- see
https://docs.python.org/3/whatsnew/3.6.html#deprecated-python-behavior.
> Fix DeprecationWarning for unrecognized backslash escapes

- CHANGES.txt
- CONTRIBUTORS.txt
- cornice/__init__.py
- cornice/errors.py
- cornice/pyramidhook.py
- docs/source/i18n.rst
- docs/source/index.rst
- tests/test_errors.py
When I add custom validation errors with `request.errors.add` method (eg. `request.errors.add('body', 'filed', _('Message'))` ) then cornice will not translate description for me. This behavior is not consistent with colander schema validation where messages are translated automatically with `request.localizer.translate` method.
This PR adds support for auto translation so it will not be necessary to call translation directly while passing description parameter to `request.errors.add`.
> Translate Error description field when it is a TranslationString type

- docs/source/index.rst
It points to a `mozilla-services` github organization which is no longer the case.
The same goes with the mailing list, but I could not find where it is now, if there is any :confused:
> Update repository URL on docs

- cornice/validators/__init__.py
- tests/test_validation.py
- tests/validationapp.py
The WebOb returned by `request.POST` supports boundary delimited `multipart/form-data` POSTs. This change merely calls the `mixed()` method on the `POST` body when the content-type is `multipart/form-data`, allowing validation to proceed in cases where the body is a combination of e.g. `json` and binary data.
> add validation support for multipart/form-data

- CHANGES.txt
- CONTRIBUTORS.txt
- cornice/validators/_marshmallow.py
- tests/validationapp.py
With this patch, keyword arguments are supported when instantiating the marshmallow schema (#511).
This is an example of how to use it:
```python
def my_validator(request, **kwargs):
if request.method == 'POST':
sch = MyPOSTSchema
kwargs['schema_kwargs'] = {'many': True}
elif request.method == 'PATCH':
sch = MyPATCHSchema
kwargs['schema'] = sch
return marshmallow_body_validator(request, **kwargs)
class MyView(object):
@view(validators=(my_validator,))
def patch(self):
return self._update()
```
So, if someone passes **schema_kwargs** dictionary in a marshmallow validator, it is expanded in the schema's constructor when it is instantiated.
Pinging @ergo for a second opinion.
> Support kwargs in marshmallow validator

- cornice/__init__.py
- cornice/renderer.py
- cornice/service.py
- cornice/util.py
- setup.py
- tests/test_errors.py
- tests/test_renderer.py
- tests/test_service.py
- tests/test_validation.py
- Makes the default cornice renderer a subclass of :class:`pyramid.renderers.JSON`, so the default rendering machinery of pyramid is still supported, while keeping the Content-Type handling logic of cornice.
- Exposes the rendering logic in :method:`cornice.renderers.CorniceRenderer.render()`, so that it's customizable if needed.
- Rationalizes the error rendering on :class:`cornice.service.Service`, so that it uses the registered render to render `request.errors`, instead of a custom function.
**BREAKING**: the default renderer does not use `simplejson.dumps` by default anymore, so the requirement has been dropped.
Mentions #531
> Refactors the rendering machinery of Cornice.

- CHANGES.txt
- docs/source/upgrading.rst
- setup.py
@devilicecream do you approve the upgrading docs?
> Prepare release 5.0

- cornice/__init__.py
- cornice/service.py
Some extensions like cornice.ext.swagger assume that JSON renderers
would contain the word ``"json"``.
Renaming this default renderer does not harm and kind of makes sense.
It does not mean we shouldn't fix the extensions to remove these sorts
of assumptions and be more robust.
> Rename default renderer to cornicejson

- cornice/validators/_colander.py
- tests/test_validation.py
- tests/validationapp.py
The issue was introduced with commit
40ed37a2f453269ab85a4376914e893cf05d89c8
Validators that had attributes like `body` was broken
(`body` was missing in `request.validated`). For example:
```python
class EmailContentSchema(MappingSchema):
subject = SchemaNode(String())
body = SchemaNode(String())
@send_email_service.post(
schema=EmailContentSchema(),
validators=(colander_body_validator,),
)
def send_email_post(request):
send_email(
request.validated["subject"],
request.validated["body"] # was missing
)
return HTTPOk()
```
The issue was with `body`, `headers`, `path`, `querystring` when using:
* `body_validator`
* `headers_validator`
* `path_validator`
* `querystring_validator`
> Fix Colander validator missing body, path, etc.

- cornice/resource.py
- tests/test_resource.py
When a Service is generated from a Resource, it losses all the attributes from the resource (specifically the docstring). This change ensures that the wrapping service looks like it wrapped resource.
This is particularly useful since when I list the services registered by Cornice (`config.registry.cornice_services`), I need to have access to the original docstring.
Since the service is based on the resource, it makes also sense to mimic its attributes.
> Copy wrapped resource's attributes into the service

- cornice/util.py
That module was deprecated since pyramid 1.7, and got removed in pyramid 2.
It was a compatibility layer for python 2 which cornice does not support since version 5
> Remove references to pyramid.compat

- cornice/validators/_marshmallow.py
- tests/requirements.txt
- tests/validationapp.py
Fixes issue #514 where **validators/_marshmallow.py** brakes when using **marshmallow 3.x**.
> fixed compatibility issues of marshmallow validator with marshmallow-3.x

- CHANGES.txt
- CONTRIBUTORS.txt
- cornice/pyramidhook.py
Use current_service to determine cornice service in pyramidhook apply_filter, previously cornice service was not found if added via pyramid_route definition.
> Fix apply_filters where service defined by pyramid_route

- cornice/validators/_marshmallow.py
After setting up a skeleton app, I was receiving a warning while running tests:
```
RemovedInMarshmallow4Warning: Passing field metadata as a keyword arg is deprecated. Use the explicit `metadata=...` argument instead.
```
The change here seems to fix the issue.
> fix: eliminate deprecated marshmallow syntax

- CHANGES.txt
- CONTRIBUTORS.txt
- tests/test_service.py
- tests/test_validation.py
The deprecated aliases have been removed in python/cpython#28268
> Use assertEqual instead of assertEquals for Python 3.11 compatibility.

- docs/source/testing.rst
- tox.ini
- use Python 3.9 instead of unsupported Python 2.7
- update `tox` command to enable running a single test
Previously, all tests were selected and coverage ran, which makes no
sense if you only run one test.
> Update documentation for `Running tests`

- docs/source/schema.rst
- docs/source/upgrading.rst
- tests/test_service.py
There are small typos in:
- docs/source/schema.rst
- docs/source/upgrading.rst
- tests/test_service.py
Fixes:
- Should read `defining` rather than `definining`.
- Should read `additional` rather than `additionnal`.
- Should read `across` rather than `accross`.
- Should read `instantiation` rather than `instanciation`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: Fix a few typos

- tests/test_resource.py
The `assert_()` method is deprecated and will be removed in Python 3.12.
```
$ python3.11
Python 3.11.4 (main, Jun  7 2023, 00:00:00) [GCC 13.1.1 20230511 (Red Hat 13.1.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from unittest2 import TestCase
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'unittest2'
>>> from unittest import TestCase
>>> TestCase.assert_
<function TestCase._deprecate.<locals>.deprecated_func at 0x7fc1cf20eac0>
```
```
$ python3.12
Python 3.12.0b3 (main, Jun 21 2023, 00:00:00) [GCC 13.1.1 20230614 (Red Hat 13.1.1-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from unittest import TestCase
>>> TestCase.assert_
Traceback (most …
```
> Use TestCase.assertTrue() instead of TestCase.assert_()
