docs/source/internals.rst

Fixes issue #225.

---

cornice/__init__.py
cornice/cors.py
cornice/ext/sphinxext.py
cornice/ext/spore.py
cornice/pyramidhook.py
cornice/resource.py
cornice/schemas.py
cornice/service.py
cornice/tests/ext/test_spore.py
cornice/tests/support.py
cornice/tests/test_cors.py
cornice/tests/test_pyramidhook.py
cornice/tests/test_resource.py
cornice/tests/test_schemas.py
cornice/tests/test_service.py
cornice/tests/test_service_description.py
cornice/tests/test_validation.py
cornice/tests/validationapp.py
cornice/util.py
setup.py
tox.ini

Flake8 pass.

---

cornice/ext/sphinxext.py

Try to mimic sphinx method args formatting for schema attributes.

Improve documentation sphinx extension

---

.travis.yml
cornice/service.py
cornice/tests/test_cors.py

It seems better to use tox for that.

Plug travis with tox

---

cornice/errors.py
cornice/resource.py
cornice/schemas.py
cornice/tests/test_cors.py
cornice/tests/test_schemas.py
cornice/tests/test_service.py
cornice/tests/test_validation.py
cornice/util.py

Otherwise, the colander validation on body (if any) may fail and throw a 500.
@leplatrem r?

Ensure passed JSON is an object.

---

CHANGES.txt
setup.py

Prepare 0.18 release.

---

cornice/cors.py
cornice/tests/test_cors.py

Wrong if clause that passed even if wrong on Python 2.*

---

cornice/schemas.py
cornice/tests/test_schemas.py

r? @Natim @leplatrem @tarekziade ?

Preserve values if colander has unknown="preserve".

---

CHANGES.txt
setup.py

Prepare 1.0.0

---

docs/source/quickstart.rst

Add a config.include('cornice') reference to the quickstart

---

CHANGES.txt
docs/source/conf.py
setup.cfg
setup.py

Prepare release 1.1.0

---

cornice/__init__.py

See https://github.com/Pylons/pyramid/blob/1.5.8/pyramid/i18n.py#L211-L218
@amarandon any objection :) ?

Remove superfluous call to get_localizer (ref #206)

---

.gitignore
CHANGES.txt
cornice/tests/test_validation.py
cornice/tests/validationapp.py
cornice/util.py
docs/source/exhaustive_list.rst
docs/source/index.rst
docs/source/testing.rst
docs/source/validation.rst

Improve documentation of content type negotiation and media type validation. See also #91, #343, #350.

Improve documentation regarding content type negotiation and media type validation

---

CHANGES.txt
CONTRIBUTORS.txt
docs/source/conf.py
setup.py

Preparing release 1.2.1

---

cornice/__init__.py

@Natim r?
As reported by @ggstuart in https://github.com/mozilla-services/cornice/commit/d390eef6681d8541b3d8ee3cdd7229b0cc3e7615#commitcomment-16813382

Use version from setup.py

---

CHANGES.txt
cornice/scaffolds/cornice/+package+.ini_tmpl

Scaffold now works when project name contains dashes (fixes #238)

---

.gitignore
Makefile

*Every PR fails because of this*.
@Natim r?

Fix docs from tox

---

cornice/pyramidhook.py
cornice/service.py
cornice/tests/validationapp.py
cornice/util.py
docs/source/validation.rst

Custom error_handler now receives the request instead of errors

---

cornice/service.py

Remove deprecated features

---

.travis.yml
CHANGES.txt
docs/source/conf.py
docs/source/quickstart.rst
setup.py

/cc @Natim @almet @tarekziade \o/

Prepare release 2.0

---

.travis.yml
cornice/validators/_colander.py
tests/requirements.txt
tests/test_pyramidhook.py
tests/test_validation.py
tox.ini

Make sure colander is optional (fixes #400)

---

docs/source/upgrading.rst

@Natim r?
/cc @amarandon : I realized that we were hasty regarding deserializers. If the upgrade path is too much pain, please let us know, we can still improve it

Deserializer upgrading docs

---

CHANGES.txt
docs/source/conf.py
setup.py

Prepare release 2.0.1

---

CHANGES.txt
cornice/util.py
cornice/validators/__init__.py
cornice/validators/_colander.py
docs/source/api.rst
docs/source/conf.py
docs/source/upgrading.rst
tests/test_util.py

Clarify situation of extract_json_data

---

CHANGES.txt
cornice/validators/_colander.py
tests/test_colander.py

Make colander_validator a no-op if no schema specified

---

CHANGES.txt
docs/source/conf.py
setup.py

Preparing release 2.1.0

---

docs/source/upgrading.rst

Document deferred validators (fixes #412)

---

CHANGES.txt
cornice/validators/__init__.py
cornice/validators/_colander.py
tests/test_validation.py
tests/validationapp.py

Add support for arrays on request body top level (fixes #433)

---

cornice/pyramidhook.py
tests/test_resource.py
tests/test_resource_callable.py

Fix to use own validator for Header Accept

---

cornice/service.py

Correct the return type of the Service acl parameter.

---

CHANGES.txt
CONTRIBUTORS.txt
cornice/pyramidhook.py
cornice/resource.py
cornice/service.py
docs/source/exhaustive_list.rst
docs/source/resources.rst
docs/source/upgrading.rst
docs/source/validation.rst
tests/test_imperative_resource.py
tests/test_pyramidhook.py
tests/test_resource.py

#452 
Dynamic `__acl__` by making the `@resource`/`@service` decorated class its own factory so its `__acl__` is used for authz

Aligning Cornice with Pyramid ACL pattern by auto-wiring factory to @resource/@service decorated class

---

CHANGES.txt
cornice/pyramidhook.py
tests/test_pyramidhook.py

Fixes #458 
/cc @DaineDanielson

Disable CSRF check on predicate fallback view (fixes #458)

---

docs/source/upgrading.rst

Correct a typo in a method signature in the docs.

---

cornice/service.py

Convert a bare except to make flake8 E722 pass.

---

CHANGES.txt
cornice/validators/__init__.py
cornice/validators/_colander.py
docs/source/api.rst
docs/source/schema.rst
setup.py

Add validators for querystring, path, and headers.

---

docs/source/tutorial.rst

I ran into some issues following the tutorial, here are the fixes I needed to complete it.
Thanks!

Make tutorial work for python3 users

---

cornice/pyramidhook.py
cornice/resource.py
tests/test_imperative_resource.py
tests/test_resource.py

Fixes https://github.com/Cornices/cornice/issues/440, by removing commits and fixing tests with conflicting declarations.

configurator: cornice should not commit configuration ever

---

docs/source/conf.py
docs/source/tutorial.rst

Fix for code block on the tutorial page:
url: https://cornice.readthedocs.io/en/latest/tutorial.html

Fix code block in tutorial.rst

---

tests/test_resource_custom_predicates.py

Ref: https://github.com/Cornices/cornice/issues/487

Remove unnecessary code in tests/test_resource_custom_predicates.py

---

cornice/validators/_marshmallow.py
tests/test_validation.py
tests/validationapp.py

This commit should normalize behavior of both Marshmallow versions.

Fix #492 - Make cornice compatible with Marshmallow 2.x and 3.x again

---

CHANGES.txt
cornice/__init__.py
cornice/pyramidhook.py
cornice/util.py
tests/test_pyramidhook.py

Ref https://github.com/Kinto/kinto/issues/1779

Remove usage of deprecated ``.best_match()``

---

CHANGES.txt
cornice/pyramidhook.py
tests/test_errors.py

Do not trigger a request.localizer when not in use.

---

CHANGES.txt
cornice/util.py
tests/test_pyramidhook.py

Do not return content if response is ``204 No Content`` (fixes #521)

---

CHANGES.txt
cornice/validators/_colander.py

Fix support of schema as class instead of instance (Fixes #523)

---

cornice/resource.py

Fix simple typo: registred -> registered

---

docs/source/tutorial.rst

I wasn’t sure where to add documentation, so I extended an example… 😁

Document combining `request.error` with Pyramid exceptions.

---

CONTRIBUTORS.txt

adds devilicecream to contributors

---

docs/source/quickstart.rst

Hello, this PR adds two important steps to the QuickStart, taken from the full tutorial.

Docs: update the quickstart tutorial

---

docs/source/index.rst

WGSI -> WSGI (Web Server Gateway Interface)

Fix a trivial typo on the doc landing page

---

tests/test_validation.py

I missed that in my previous pull request

Removed missed compat import from tests

---

cornice/resource.py

Frame was always set to 2 for resource decorator.

---

CHANGES.txt
cornice/validators/_marshmallow.py
tests/requirements.txt
tests/test_validation.py
tests/validationapp.py

Marshmallow 3.x

---

cornice/pyramidhook.py

Add deserializer to cornice params
